export { default as Home } from '../pages/Home'
export {default as Explore } from '../pages/Explore'
export {default as Saved } from '../pages/Saved'
export {default as CreatePost } from '../pages/CreatePost'
export {default as EditPost } from '../pages/EditPost'
export {default as PostDetails } from '../pages/PostDetails'
export {default as AllUsers } from '../pages/AllUsers'
export {default as Profile } from '../pages/Profile'
export {default as UpdatedProfile } from '../pages/UpdateProfile'
export {default as LikedPosts } from '../pages/LikedPosts'